### ISSUE TITLE
InvalidSceneFileProtection creates long load times on Large Scenes

### ISSUE THREAD

**Issue by TicklefistVN** [IllusionMods/IllusionFixes#17]
Scenes with lots of characters and objects, especially large scenes exceeding 150mb, will have long load times, exceeding 20 minutes in some cases. Removing the plugin will get rid of the issue.

**Comment by ManlyMarco** [comment]
It should be much better in d140e07293e8c939199e42beed40cf13da073a66
The slowdown is caused by a check to see if the scene is for the correct game and actually contains scene data. 

It's still not perfect but for now I call it good enough. You can bypass the check by dragging the scene into game window instead of using the ingame ui.

**Comment by leoftm** [comment]
I think this specification is recurring.

**Comment by ManlyMarco** [comment]
> I think this specification is recurring.

This plugin was not changed at all since this change I believe, so that's very unlikely.
