### ISSUE TITLE
Reducing stutter and FPS drop in HoneySelect 2 (port GarbageTruck to HS2)

### ISSUE THREAD

**Issue by EduardDiego** [IllusionMods/IllusionFixes#22]
Seems like the game has this is an issue with Garbage Collector, because it rising up like crazy from 700 to 1000 mb and then resets back with significant FPS drop. This repeats every 4-7 seconds. You can see it clearly entering character creation menu and using mod called FPS counter. The issue was detected on DX R2 repack of the game.
Also have to append something: looks like boy character screen gathers "garbage" slower, than girl's one (which leads to less frequent stutters). Might be something with mods count (because, ofc, boys has less mods). And it also slower in StudioNeoV2, for some reason.
I don't know if its even possible to fix with mods and dll's, but it would be great to have something like GarbageTruck\MainGameOptimizations in Koikatsu but for HS2.

**Comment by ManlyMarco** [comment]
GarbageTruck is meant to address this exact issue, and it does a decent job at it in KK. The collections still happen but they are much rarer and faster.

The issue is that it's very game-specific and porting it would be close to writing it from scratch. No one seems to be motivated to do it at the moment since it takes a decent amount of work to profile the sources of garbage, figure out how to patch them out, and then test and fix the inevitable compatibility issues with other plugins.

**Comment by ManlyMarco** [comment]
Solved for the most part in df1f256d8ce82ee05e5677037238ab8ee7fbd088. There are probably more sources of garbage that can be fixed, but this should put a dent in it at least.
