### ISSUE TITLE
[KK]For problems with twisted legs and misaligned hands

### ISSUE THREAD

**Issue by stosto322** [IllusionMods/IllusionFixes#32]
Sorry, this is an issue that spans multiple plugins, but I have posted the issue here. I would appreciate it if you could let me know if there is a problem.

In Maker, if I use ABMX and set cf_j_waist01 or cf_j_waist02 to less than 1, there is a problem with twisting of the legs and shifting of the hand position.
![image](https://user-images.githubusercontent.com/89012118/137621655-ef20b849-f98b-4ca9-b6de-c5661e330e79.png)

I have confirmed that this problem does not occur when KK_Fix_MakerOptimizetions of version 1.8 or higher and version 13.1 or lower is installed.

The version of ABMX does not seem to affect this issue.

In Maingame, the problem seems to occur regardless of the version of KK_Fix_MainGameOptimizetions.

As an additional note, this problem does not occur in koikatsuSunshine when KK_Fix_MakerOptimizetions is installed on version 18.0.1.

If you need any additional information, please let me know.

Sorry for my poor English.

**Comment by ManlyMarco** [comment]
It's a known issue caused by the "Disable maker IK" setting in combination with Stiletto. Either Stiletto will be broken or you will get the issue seen above. There is no fix that will completely fix these two issues currently. You can remove Stiletto and toggle the "Disable maker IK" setting to fix this but poses won't get adjusted with high heels on and the character will likely look broken for other people if you share it.

**Comment by stosto322** [comment]
Thank you for your reply!

I did remove the Stiletto and switched the "Disable maker IK" setting and the twisting of the legs went away, so I'm pretty sure it's the same problem.

I'm sorry that I missed the fact that this is a known issue.
